$ErrorActionPreference = 'Stop'

$packageName = 'noetica'
$installDir  = "$env:ProgramFiles\Noetica"
$servicePort = 8080

New-Item -ItemType Directory -Force -Path $installDir | Out-Null

# ── Download Noetica release ──────────────────────────────────────────────────
$releaseBase = 'https://github.com/socioprophet/Noetica/releases/latest/download'
$buildAvailable = $false
try {
  $h = Invoke-WebRequest -Uri "$releaseBase/noetica-win64.zip" -Method Head -UseBasicParsing -TimeoutSec 5 -ErrorAction Stop
  $buildAvailable = ($h.StatusCode -eq 200)
} catch { $buildAvailable = $false }

if ($buildAvailable) {
  Write-Host "Installing Noetica from release..."
  Install-ChocolateyZipPackage -PackageName $packageName `
    -Url64bit "$releaseBase/noetica-win64.zip" `
    -UnzipLocation $installDir `
    -Checksum64 'SKIP' -ChecksumType64 'sha256'
} else {
  Write-Host "No pre-built release found — cloning from source..." -ForegroundColor Yellow

  # Check for Node.js
  $node = Get-Command node -ErrorAction SilentlyContinue
  if (-not $node) { throw "Node.js is required. Install with: choco install nodejs" }

  $git = Get-Command git -ErrorAction SilentlyContinue
  if ($git) {
    Write-Host "Cloning Noetica..."
    & git clone --depth 1 https://github.com/socioprophet/Noetica.git $installDir 2>&1 | Out-Null
    Push-Location $installDir
    & npm install --production 2>&1 | Out-Null
    Pop-Location
    Write-Host "  Noetica cloned and dependencies installed." -ForegroundColor Green
  } else {
    Write-Warning "git not found. Install with: choco install git"
    Write-Warning "Then run: git clone https://github.com/socioprophet/Noetica.git `"$installDir`""
  }
}

# ── Windows Service via NSSM ──────────────────────────────────────────────────
# Try to use NSSM (Non-Sucking Service Manager) for reliable service management
$nssmPath = Get-Command nssm -ErrorAction SilentlyContinue
if (-not $nssmPath) {
  # Install NSSM via Chocolatey
  try {
    choco install nssm --yes --no-progress 2>&1 | Out-Null
    $nssmPath = Get-Command nssm -ErrorAction SilentlyContinue
  } catch {
    Write-Warning "NSSM not available — Noetica will not run as a Windows service."
    Write-Warning "Start manually: node `"$installDir\app\server.js`" or npm start in $installDir"
  }
}

# Find the server entry point
$serverEntries = @(
  "$installDir\app\server.js",
  "$installDir\server.js",
  "$installDir\src\server.js",
  "$installDir\index.js"
)
$serverEntry = $null
foreach ($entry in $serverEntries) {
  if (Test-Path $entry) { $serverEntry = $entry; break }
}

# Fallback: create a launcher script
if (-not $serverEntry) {
  $launcherContent = @"
// Noetica Windows launcher
// Auto-generated by Chocolatey installer
const { execSync } = require('child_process');
const path = require('path');
const installDir = path.dirname(__filename);
try {
  process.chdir(installDir);
  require(path.join(installDir, 'app', 'server') ||
          path.join(installDir, 'server') ||
          path.join(installDir, 'index'));
} catch(e) {
  const pkg = require(path.join(installDir, 'package.json'));
  const main = pkg.main || 'index.js';
  require(path.join(installDir, main));
}
"@
  $launcherPath = "$installDir\noetica-launcher.js"
  Set-Content -Path $launcherPath -Value $launcherContent -Encoding UTF8
  $serverEntry = $launcherPath
}

# Write startup config
$configContent = @"
{
  "port": $servicePort,
  "host": "127.0.0.1",
  "platform": "windows",
  "service": true,
  "logFile": "$($env:APPDATA -replace '\\','/')/noetica/noetica.log"
}
"@
$configDir = "$env:APPDATA\noetica"
New-Item -ItemType Directory -Force -Path $configDir | Out-Null
Set-Content -Path "$configDir\config.json" -Value $configContent -Encoding UTF8

# Install as Windows service if NSSM available
if ($nssmPath -and $serverEntry) {
  $nodeExe = (Get-Command node).Source

  # Remove existing service if present
  $existing = Get-Service -Name 'Noetica' -ErrorAction SilentlyContinue
  if ($existing) {
    Stop-Service -Name 'Noetica' -Force -ErrorAction SilentlyContinue
    & nssm remove Noetica confirm 2>&1 | Out-Null
  }

  # Install service
  & nssm install Noetica $nodeExe $serverEntry
  & nssm set Noetica AppDirectory $installDir
  & nssm set Noetica AppEnvironmentExtra "PORT=$servicePort" "NODE_ENV=production" "NOETICA_CONFIG=$configDir\config.json"
  & nssm set Noetica DisplayName "Noetica AI Backend"
  & nssm set Noetica Description "Self-hosted AI dialogue management backend for TurtleTerm co-pilot and NL-to-shell features."
  & nssm set Noetica Start SERVICE_AUTO_START
  & nssm set Noetica AppStdout "$configDir\noetica.log"
  & nssm set Noetica AppStderr "$configDir\noetica-error.log"
  & nssm set Noetica AppRotateFiles 1
  & nssm set Noetica AppRotateSeconds 86400

  Start-Service -Name 'Noetica' -ErrorAction SilentlyContinue

  # Wait up to 10s for health check
  $healthy = $false
  for ($i = 0; $i -lt 10; $i++) {
    Start-Sleep -Seconds 1
    try {
      $h = Invoke-RestMethod -Uri "http://localhost:$servicePort/health" -TimeoutSec 2 -ErrorAction Stop
      $healthy = $true; break
    } catch {}
  }

  if ($healthy) {
    Write-Host ""
    Write-Host "Noetica v0.4.11 running as Windows service." -ForegroundColor Green
    Write-Host "  Port    : http://localhost:$servicePort"
    Write-Host "  Logs    : $configDir\noetica.log"
    Write-Host "  Service : sc query Noetica"
  } else {
    Write-Warning "Noetica service started but health check timed out."
    Write-Warning "Check logs: $configDir\noetica-error.log"
  }
} else {
  Write-Host ""
  Write-Host "Noetica installed at $installDir" -ForegroundColor Green
  Write-Host "  Start: node `"$serverEntry`""
  Write-Host "  Or:    npm start (in $installDir)"
  Write-Host "  Health: http://localhost:$servicePort/health"
}

# ── Set environment variable for TurtleTerm integration ───────────────────────
[Environment]::SetEnvironmentVariable('SOURCEOS_NOETICA_URL', "http://localhost:$servicePort", 'Machine')

# ── Create PowerShell management functions ────────────────────────────────────
$mgmtScript = @"
# Noetica management functions — auto-generated by Chocolatey installer

function Start-Noetica {
  Start-Service Noetica
  Write-Host 'Noetica started. Health: ' -NoNewline
  try { (Invoke-RestMethod http://localhost:$servicePort/health).status } catch { 'checking...' }
}

function Stop-Noetica {
  Stop-Service Noetica
  Write-Host 'Noetica stopped.'
}

function Get-NoeticalHealth {
  try {
    Invoke-RestMethod http://localhost:$servicePort/health | ConvertTo-Json
  } catch {
    Write-Warning 'Noetica not responding on :$servicePort'
  }
}

function Invoke-NoetliaChat {
  param([string]`$Message)
  Invoke-RestMethod -Method POST -Uri 'http://localhost:$servicePort/api/chat' ``
    -ContentType 'application/json' ``
    -Body (ConvertTo-Json @{ message = `$Message })
}

Set-Alias noetica-start  Start-Noetica
Set-Alias noetica-stop   Stop-Noetica
Set-Alias noetica-health Get-NoeticalHealth
Set-Alias noetica-chat   Invoke-NoetliaChat
"@
Set-Content -Path "$installDir\noetica-management.ps1" -Value $mgmtScript -Encoding UTF8

Write-Host ""
Write-Host "  TurtleTerm integration:"
Write-Host "    `$env:SOURCEOS_NOETICA_URL = 'http://localhost:$servicePort'"
Write-Host "    turtle-copilot use noetica"
Write-Host "    turtle-copilot start"
