// AUTO-GENERATED by scripts/meta_combiner.py — do not edit by hand.
// trained on transcript.jsonl (n=199), softmax test acc 52.9%.
// The signed weights ARE the council, learned from evidence — deployed via learnedCouncilVote (lib/council.ts).
export const COUNCIL_WEIGHTS = {
  "version": "1",
  "arms": [
    "baseline",
    "brain",
    "qgen",
    "gate",
    "medprompt",
    "elim",
    "fiftyfifty",
    "compute"
  ],
  "feats": [
    "baseline",
    "brain",
    "qgen",
    "gate",
    "medprompt",
    "elim",
    "fiftyfifty",
    "compute",
    "isA"
  ],
  "bias": -0.4795,
  "w": {
    "baseline": -0.5461,
    "brain": 0.757,
    "qgen": -0.2756,
    "gate": 0.3205,
    "medprompt": 1.5206,
    "elim": 0.177,
    "fiftyfifty": -0.2251,
    "compute": 0.2334,
    "isA": -0.3409
  },
  "isA": -0.3409,
  "softmax_test_acc": 0.5286,
  "symbolic_law": "mul(compute, 0.139)",
  "trained_on": "transcript.jsonl",
  "n_questions": 199
} as const
