#!/usr/bin/env -S node --import tsx
/**
 * cost-teeup — render the WS-A (fine-tuning) + WS-C (cloud-mesh proof) run-cost tee-up off the CANONICAL
 * gpu-catalog via the broker, so the numbers track the single source of truth. Prints markdown to stdout:
 *   node --import tsx agent-machine/scripts/cost-teeup.ts > docs/WS-A-WS-C-COST-TEEUP.md
 * Edit the WS_A / WS_C scenarios in lib/cost-estimator.ts to match the real planned runs, then re-render.
 */
import { WS_A, WS_C, renderEstimate, estimateAll } from "../lib/cost-estimator.js";

const a = estimateAll(WS_A);
const c = estimateAll(WS_C);
const phase1Total = [...a, ...c].reduce((s, r) => s + r.totalUsd, 0);

const provs = new Set([...a, ...c].map((r) => r.provider));

console.log(`<!-- generated by agent-machine/scripts/cost-teeup.ts — do not hand-edit; edit lib/cost-estimator.ts scenarios -->`);
console.log(`# Prove-on-Metal — WS-A + WS-C run-cost tee-up\n`);
console.log(`Itemized, brokered to the **cheapest compliant supply** in the canonical \`gpu-catalog.v1.json\` (spot where noted).`);
console.log(`These are *one-off run costs* (bill only while the job runs), not the monthly opex in \`scripts/cost-report.mjs\`.\n`);
console.log(renderEstimate("WS-A · Fine-tuning (KubeRay + TritFabric LoRA trainer)", WS_A));
console.log("");
console.log(renderEstimate("WS-C · Cloud-mesh proof (beats-frontier-on-your-tests, flat cost)", WS_C));
console.log(`\n---\n`);
console.log(`## Phase-1 envelope`);
console.log(`- **One-off (WS-A fine-tunes + WS-C bursts, excl. the 730h/mo Ray Serve baseline): $${(phase1Total - (a.find((r) => r.hours >= 730)?.totalUsd ?? 0)).toFixed(2)}**`);
console.log(`- **WS-A Ray Serve choir baseline (24/7, 1×L4): $${(a.find((r) => r.hours >= 730)?.totalUsd ?? 0).toFixed(2)}/mo** (the only recurring line)`);
console.log(`- Cheapest-supply providers selected this run: ${[...provs].join(", ")}`);
console.log(`\n> Re-run after a catalog refresh or a live-billing adapter swap — shape is stable, only the numbers move.`);
